### ISSUE TITLE
Make linuxrc translatable

### ISSUE THREAD

**Issue by scootergrisen** [openSUSE/linuxrc#142]
I see linuxrc when installation openSuse but the strings does not appear to be translated.
I can't seem to find any info about translating linuxrc so i would like to suggest making it translatable so i can translate it into my language for a more complete translated experience for the user.

**Comment by wfeldt** [comment]
linuxrc used to be translatable in the past. It was removed around sle12 times (with version 4.2.0) to reduce complexity. The main reason is that the interactive part of linuxrc (the 'manual' mode) is only rarely used.
