### ISSUE TITLE
Wrong network configuration after install, when pass parameters with vlan

### ISSUE THREAD

**Issue by 6aKa** [openSUSE/linuxrc#228]
Step for reproduce:

1. When install openSUSE Tumbleweed, config network with vlan on one interface with parameters "Boot options", example
ifcfg="eno1.55=192.168.10.10/24,192.168.10.1,1.1.1.1 8.8.4.4 8.8.8.8,mydomain.com"
2. After install run yast2, System -> Network Settings, than select eno1.55 interface and press edit.

Empty VLAN ID field, but expected 55.
And if change hostname and save - you got broken network.

**Comment by teclator** [comment]
Looks like the bug is duplicated as it has been also reported in https://github.com/yast/yast-network/issues/1103, so, will close this one as it looks related to yast-network instead of linuxrc
